version: '3.4'

services:
  eventsapp.api:
    image: events-api
    build:
      context: .
      dockerfile: EventsApp.API/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      SA_PASSWORD: "SwN12345678"
      ACCEPT_EULA: "Y"